# Lab1 część pierwsza

## Praca z biblioteką NumPy

Pierwszym krokiem przy pracy z biblioteką NumPy jest jej import. Można tego dokonać za pomocą polecenia **import numpy**. Dodatkowo można dodać alias, który będzie stanowił skrót nazwy przy odwoływaniu w kodzie źródłowym do funkcjonalności oferowanych przez bibliotekę:

In [1]:
import numpy as np  # importujemy numpy pod nazwa np i wtedy do biblioteki zamiast pelna nazwa odwolujemy sie np (uruchomic shift + enter)

### Tworzenie nowych tablic na podstawie list

Najprostszą metodą utworzenia tablicy NumPy jest przekazanie listy wartości do funkcji array z pakietu NumPy:

In [2]:
# tablica otypowana jako np.ndarray utworzona ze zwyklej listy pythonowej
# w typie np.ndarray nie definiujemy typu zawartosci jak np List[int] tylko ogolnie ze jest to tablica numpy
arr: np.ndarray = np.array([1, 2, 3, 4, 5])

print(arr)  # wypisujemy tablice
print(type(arr))  # wypisujemy typ tej zmiennej czyli jest to tablica numpy (np.ndarray)

[1 2 3 4 5]
<class 'numpy.ndarray'>


W podobny sposób można tworzyć również tablice wielowymiarowe (tensory). W tym celu należy przekazać do funkcji array z pakietu NumPy listę wielowymiarową.

In [3]:
arr_2d: np.ndarray = np.array([  # tworzymy macierz z listy 2D pythonowej, czyli powstanie tablica numpy 2D czyli macierz
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
])

arr_2d  # tutaj jezeli to ostatnie wyrazenie w komorce to nie jest potrzebny print

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

### Typy danych w NumPy

Typy danych w bibliotece NumPy definiują charakter wartości przechowywanych w tablicach. Typ może zostać ustalony automatycznie bądź wskazany manualnie (w celu optymalizacji pamięci) za pomocą parametru dtype.

In [4]:
# tworzymy tablice gdzie wskazujemy ze zawartosc ma byc typu int, inaczej numpy sam dopasuje typ zawartosci nie zawsze optymalny
arr_int: np.ndarray = np.array([1, 2, 3, 4, 5], dtype='i')

arr_int

array([1, 2, 3, 4, 5], dtype=int32)

Typ wartości w tablicy można sprawdzić za pomocą atrybutu dtype.

In [5]:
arr_int.dtype  # tez bez printa bo to jupyter, typ wartosci ktore sa w tablicy

dtype('int32')

### Podstawowe typy danych w NumPy

Wyróżniamy następujące podstawowe typy danych występujące w bibliotece NumPy
- i - integer (wartośc całkowita)
- b - boolean (wartość logiczna)
- u - unsigned integer (wartość całkowita >= 0)
- f - float (wartość rzeczywista)
- c - complex float (wartość zespolona zmiennoprzecinkowa)
- m - timedelta (wartość przesuniecia czasu)
- M - datetime (wartość czasu)
- O - object (dowolny obiekt)
- S - string (tekst)
- U - unicode string (tekst w formacie unicode)
- V - fixed chunk of memory for other type (wartość bliżej nieokreślona)

### Złożone typy danych w NumPy

W typie danych można również wskazać ilość zarezerwowanego miejsca na wartość. Przykładowo, "i4" oznacza typ integer (całkowitoliczbowy) 4-bajtowy.

In [ ]:
arr: np.ndarray = np.array([1, 2, 3, 4, 5], dtype='i4')  # tablica z listy pythonowej

print(arr)  # wypisanie tablicy
print(arr.dtype)  # wypisanie typu zawartosci w tablicy

[1 2 3 4 5]
int32


### Tworzenie tablic przy użyciu funkcji numpy

Pakiet NumPy umożliwia również tworzenie tablic wypełnionych wartościami.
Funkcja zeros służy do tworzenia tablic o wskazanym rozmiarze, wypełnionych zerami:



In [ ]:
np.zeros(10, dtype='i')  # funkcja zwraca macierz wiec nie trzeba teraz podstawiac do zmiennej i od razu sie wypisze w Jupyter

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

Funkcji zeros można również użyć do tworzenia tablic wielowymiarowych:

In [ ]:
np.zeros((5, 5))  # tutaj jezeli wiecej niz 1 wymiar to wymiary wskazujemy w krotce (5,5) lub (3,3,5) itd czyli podwojne nawiasy

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Bardzo podobne zastosowanie ma funkcja ones, która tworzy tablice wypełnione jedynkami:

In [ ]:
np.ones((3, 3))  # tu tak samo

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Do stworzenia przestrzeni liniowej o wskazanym zakresie i liczbie elementów należy użyć funkcji linspace

In [ ]:
np.linspace(0, 10, 6)  # 6 elementow w zakresie 0-10 gdzie 10 tez wchodzi w gre

array([ 0.,  2.,  4.,  6.,  8., 10.])

Funkcja eye utworzy macierz jednostkową (kwadratową) o wskazanym rozmiarze:

In [ ]:
np.eye(5)  # to zwroci macierz kwadratowa wiec wskazujesz tylko 1 wymiar

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Za pomocą funkcji rand pochodzącej z modułu random w pakiecie NumPy można wygenerować tensor o wskazanym rozmiarze zawierający wartości losowe pochodzące z rozkładu normalnego jednorodnego, w przedziale [0-1):

In [ ]:
np.random.rand(5)  # wektor liczb losowych w zakresie od 0 do 1 (nie dosiega samej 1)

array([0.96189274, 0.73487489, 0.49444472, 0.57159979, 0.97587037])

In [ ]:
np.random.rand(3, 2)  # a tutaj to samo tylko macierz

array([[0.15035923, 0.56635759],
       [0.99309627, 0.84747083],
       [0.54918642, 0.86910955]])

Funkcja randn pochodząca z modułu random w pakiecie NumPy ma podobne zastosowanie do funkcji rand. Różnica między nimi polega na generowaniu wartości losowych pochodzących z rozkładu normalnego:

In [ ]:
np.random.randn(5, 5)  # tutaj to samo co wyzej tylko rozklad ma srednia 0 i odch std 1

array([[ 1.09223132,  1.01134174, -0.204271  ,  0.05773278,  1.02402038],
       [-0.18451507,  0.74529921, -1.23540266,  0.29378047,  0.54391971],
       [ 0.3021809 ,  0.41627912,  0.00390165,  0.02613831,  0.02634542],
       [-0.62427156, -1.70773967, -0.62768729,  0.20094255, -0.35074538],
       [-0.68028963,  1.20120128, -0.16436656,  0.28659376, -2.08525135]])

Funkcja randint pochodząca z modułu random w pakiecie NumPy ma również podobne zastosowanie do swoich poprzedniczek. Różnica polega na generowaniu wartości losowych z wyznaczonych przedziałów:

In [ ]:
np.random.randint(1, 49, (3, 6))  # tutaj najpierw wskazujemy poczatek zakresu, koniec i ksztalt tensora w krotce (losowe liczby calkowite)

array([[33, 33,  2, 46, 31, 17],
       [ 2,  4, 42, 26, 46,  7],
       [48,  9, 10, 17, 38, 12]])

### Indeksowanie danych w tablicach

Biblioteka NumPy umożliwia wygodne wybieranie wartości znajdujących się w tablicach za pomocą wskazania ich pozycji.

In [ ]:
arr_2d: np.ndarray = np.array([  # tworzymy jakas macierz z listy 2D
                               [5, 10, 15],
                               [20, 25, 30],
                               [35, 40, 45]
])

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Wiersz z takiej tablicy można pobrać wskazując jego indeks:

In [ ]:
arr_2d[0]  # wyswietlamy pierwszy wiersz pod indeksem 0

array([ 5, 10, 15])

Wartośc skalarną można pobrać wskazując jej konkretną pozycję w formacie [wiersz, kolumna]:

In [ ]:
arr_2d[1, 2]  # a tutaj wartosc w wierszu o id 1 i komorce o id 2 liczac od 0

30

Kolumnę z tablicy można pobrać wskazując wszystkie wiersze za pomocą znaku : oraz indeks kolumny w następującym formacie [:, col]:

In [ ]:
arr_2d[:, 1]  # to jest jak wybieranie pojedynczej wartosci z komorki ale : wskazuje wszystkie wartosci w danym wymiarze (tutaj w wierszach)

array([10, 25, 40])

Za pomocą indeksu -1 można pobrać ostatnią wartość we wskazanym wymiarze:

In [ ]:
arr_2d[-1, -1]  # -1 to indeks ostatniej wartosci

45

Biblioteka NumPy umożliwia również pobieranie podtablic za pomocą zakresów indeksów wskazanych w konkretnych wymiarach:

In [ ]:
matrix: np.ndarray = np.random.randint(1, 100, (5, 5))  # generujemy na pozniej jakas macierz losowa 5 wierszy 5 kolumn

matrix

array([[67, 23, 65, 72, 81],
       [46, 53, 48, 83, 48],
       [82, 26, 22, 86, 17],
       [40, 39, 22, 53, 19],
       [54, 69, 22, 93, 35]])

In [ ]:
matrix[1:4, 1:4]  # wybieramy wszystkie wiersze o id od 1 do 4 (bez 4) i z tych wierszy kolumny o id od 1 do 4 (bez 4)

array([[53, 48, 83],
       [26, 22, 86],
       [39, 22, 53]])

### Kształt tablicy i jego modyfikacja

Kształt tablicy można sprawdzić za pomocą atrybutu shape:

In [ ]:
arr: np.ndarray = np.ones((5, 4))  # tablica jedynek 5 wierszy 4 kolumny

print(arr)  # wyswietlenie tablicy
print(arr.shape)  # wyswietlenie ksztaltu tej tablicy czyli ile wierszy i ile kolumn

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(5, 4)


Wynik (5, 4) informuje nas o 5 wierszach i 4 kolumnach macierzy.

Za pomocą metody reshape można zmodyfikować kształt tablicy.

In [ ]:
arr: np.ndarray = np.ones(25)  # tablica (wektor) z 25 jedynkami (na pozniej)

arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr.reshape((5, 5))  # zamiana wektora 25 elementowego na macierz 5 wierszy 5 kolumn (liczba elementow musi sie zgadzac)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Wyszukiwanie w tablicach wartości największych i najmniejszych

In [ ]:
arr: np.ndarray = np.random.randint(1, 100, 10)  # wektor (tablica) 10 liczb calkowitych losowych od 1 do 100

arr

array([50, 74, 13, 43, 87, 58, 14, 61, 82, 51])

Za pomocą metody min można znaleźć wartość największą:

In [ ]:
arr.min()

13

Wartość największą można znaleźć za pomocą metody max:

In [ ]:
arr.max()

87

Pozycję elementu o największej lub najmniejszej wartości można znaleźć za pomocą metod argmax i argmin:

In [ ]:
print(f'wartosc najwieksza: {arr.max()}, pozycja wartosci najwiekszej: {arr.argmax()}')  # metoda argmin() zwraca id najmniejszego elementu
print(f'wartosc najmniejsza: {arr.min()}, pozycja wartosci najmniejszej: {arr.argmin()}')  # argmax() analogicznie
# te metody sa wywolane na obiekcie tablicy o nazwie arr: arr.argmin() itd

wartosc najwieksza: 87, pozycja wartosci najwiekszej: 4
wartosc najmniejsza: 13, pozycja wartosci najmniejszej: 2


### Funkcje matematyczne w NumPy

Pakiet NumPy dostarcza wiele funkcji matematycznych dokonujących operacji na wszystkich elementach tablic.

In [ ]:
arr: np.ndarray = np.arange(11)  # generujemy kolejne wartosci od 0 do 10

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Za pomocą funkcji sqrt można obliczyć pierwiastki kwadratowe wszystkich elementów znajdujących się w tablicy:

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

Za pomocą funkcji exp można wyznaczyć wartość wyrażenia $$e ^ x$$ gdzie x to każdy kolejny element znajdujący się w tablicy:

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

### Arytmetyka i algebra tensorów

Pakiet NumPy umożliwia również wygodne dokonywanie działań arytmetycznych oraz algebraicznych na tablicach:

In [ ]:
arr0: np.ndarray = np.random.randint(1, 10, (3, 3))  # losowa macierz 3x3 wartosci od 1 do 10
arr1: np.ndarray = np.random.randint(1, 10, (3, 3))

print(arr0)  # wysw pierwszej macierzy
print('--------')  # separator
print(arr1)  # wysw drugiej macierzy

[[2 9 5]
 [6 1 6]
 [5 1 8]]
--------
[[7 1 4]
 [7 5 8]
 [8 1 6]]


Działań arytmetycznych na tablicach można dokonać za pomocą klasycznych operatorów arytmetycznych:

In [ ]:
arr0 + arr1

array([[ 9, 10,  9],
       [13,  6, 14],
       [13,  2, 14]])

In [ ]:
arr0 - arr1

array([[-5,  8,  1],
       [-1, -4, -2],
       [-3,  0,  2]])

In [ ]:
arr0 * arr1

array([[14,  9, 20],
       [42,  5, 48],
       [40,  1, 48]])

In [ ]:
arr0 ** 2

array([[ 4, 81, 25],
       [36,  1, 36],
       [25,  1, 64]])

Pakiet NumPy udostępnia również interfejs do dokonywania operacji algebraicznych na tensorach.
Do wyznaczenia iloczynu skalarnego dwóch tensorów służy metoda dot:

In [ ]:
arr0.dot(arr1)  # iloczyn skalarny dwoch macierzy

array([[117,  52, 110],
       [ 97,  17,  68],
       [106,  18,  76]])

lub analogicznie:

In [ ]:
arr0[0].dot(arr1[1])  # # iloczyn skalarny pierwszego wiersza macierzy 1 i drugiego wiersza macierzy 2

99

## Zadania

1. Utworzyć tablicę zawierającą 50 piątek.
2. Utworzyć tablicę o rozmiarach 5x5 z wartościami od 1 do 25.
3. Utworzyć tablicę tablicę liczb parzystych od 10 do 50.
4. Utworzyć macierz, w której na przekątnej znajdą się wartości równe 8, a pozostałe będą wynosiły 0.
5. Utworzyć tablicę o rozmiarach 10x10 z wartościami zwiększającymi się o 0.01.
6. Utworzyć przestrzeń liniową 50 wartości z zakresu 0-1.
7. Wybrać podtablicę 12-elementową, z tablicy utworzonej w zadaniu 2, z wartościami w zakresie 12-25.
8. Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę.
9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2.
10. Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów.
11. Przygotować macierz, która w każdym wierszu będzie zawierała wartości od 1 do 5. Uwaga, nie używać w tym celu gotowych list do utworzenia macierzy.
12. Utworzyć wektor 10-elementowy składający się z wartości losowych, a następnie wstawić 0 w miejsce wartości najmniejszej.
13. Napisać skrypt, który w losowym wektorze Z znajdzie najbliższą wartość losowego skalara v.
14. Wygenerować losową macierz M o rozmiarach 5x8, a następnie zamienić kolejnością 2 losowo wskazane wiersze.
15. Wygenerować macierz o rozmiarach 5x5 wypełnioną dowolnymi kolejnymi wartościami, a następnie przetransformować macierz do postaci wektora kolumnowego zachowując wszystkie wartości.