## Zadania

1. Utworzyć tablicę zawierającą 50 piątek.

In [1]:
import numpy as np

fives_array = np.full(50, 5)

print(fives_array)

[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 5 5 5 5]


2. Utworzyć tablicę o rozmiarach 5x5 z wartościami od 1 do 25.

In [2]:
import numpy as np

array_5x5 = np.arange(1, 26).reshape(5, 5)

print(array_5x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


3. Utworzyć tablicę tablicę liczb parzystych od 10 do 50.

In [3]:
import numpy as np

even_array = np.arange(10, 51, 2)

print(even_array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


4. Utworzyć macierz, w której na przekątnej znajdą się wartości równe 8, a pozostałe będą wynosiły 0.

In [4]:
import numpy as np

# Utworzenie macierzy zerowej o wymiarach 5x5
matrix = np.zeros((5, 5))

# Zaktualizowanie wartości na przekątnej na 8
np.fill_diagonal(matrix, 8)

print(matrix)

[[8. 0. 0. 0. 0.]
 [0. 8. 0. 0. 0.]
 [0. 0. 8. 0. 0.]
 [0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 8.]]


5. Utworzyć tablicę o rozmiarach 10x10 z wartościami zwiększającymi się o 0.01.

In [5]:
import numpy as np

# Utworzenie tablicy 10x10 z wartościami zwiększającymi się o 0.01
array_10x10 = np.arange(0, 1, 0.01).reshape(10, 10)

print(array_10x10)

[[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09]
 [0.1  0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19]
 [0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29]
 [0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39]
 [0.4  0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49]
 [0.5  0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59]
 [0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69]
 [0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79]
 [0.8  0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89]
 [0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99]]


6. Utworzyć przestrzeń liniową 50 wartości z zakresu 0-1.

In [6]:
import numpy as np

# Utworzenie przestrzeni liniowej z 50 wartościami w zakresie od 0 do 1
linear_space = np.linspace(0, 1, 50)

print(linear_space)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


7. Wybrać podtablicę 12-elementową, z tablicy utworzonej w zadaniu 2, z wartościami w zakresie 12-25.

In [7]:
import numpy as np

linear_space = np.linspace(0, 1, 50)

subarray = linear_space[12:26]

print(subarray)

[0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408]


8. Wybrać 3 pierwsze elementy z ostatniej kolumny tablicy utworzonej w zadaniu 2, a następnie ułożyć z nich kolumnę.

In [9]:
last_column_elements = array_5x5[:3, -1]

column = last_column_elements.reshape(-1, 1)

print(column)

[[ 5]
 [10]
 [15]]


9. Wyznaczyć sumę wartości elementów znajdujących się w dwóch ostatnich wierszach macierzy utworzonej w zadaniu 2.

In [10]:
sum_last_two_rows = np.sum(array_5x5[-2:], axis=0)
print("Suma wartości elementów w dwóch ostatnich wierszach:")
print(sum_last_two_rows)

Suma wartości elementów w dwóch ostatnich wierszach:
[37 39 41 43 45]


10. Przygotować skrypt, który stworzy tensor zawierający losowe wartości całkowite, losowym wymiarze i losowym rozmiarze każdego z wymiarów.

In [19]:
# Losowy wymiar od 1 do 4
random_dimension = np.random.randint(1, 5) 

# Losowe rozmiary dla każdego z wymiarów
random_sizes = np.random.randint(1, 10, size=random_dimension)

# Generowanie tensora z losowymi wartościami całkowitymi
random_tensor = np.random.randint(1, 100, size=random_sizes)

# Wyświetlenie wyników
print("Losowy wymiar:", random_dimension)
print("Losowe rozmiary dla każdego z wymiarów:", random_sizes)
print("Tensor z losowymi wartościami całkowitymi:")
print(random_tensor)

Losowy wymiar: 1
Losowe rozmiary dla każdego z wymiarów: [5]
Tensor z losowymi wartościami całkowitymi:
[54 81 99 78 64]


11. Przygotować macierz, która w każdym wierszu będzie zawierała wartości od 1 do 5. Uwaga, nie używać w tym celu gotowych list do utworzenia macierzy.

In [20]:
rows = 5
cols = 5

matrix = np.empty((rows, cols))

for i in range(rows):
    matrix[i] = np.arange(1, cols + 1)

print(matrix)

[[1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]
 [1. 2. 3. 4. 5.]]


12. Utworzyć wektor 10-elementowy składający się z wartości losowych, a następnie wstawić 0 w miejsce wartości najmniejszej.

In [22]:
vector = np.random.randint(1, 100, size=10)

# Wstawienie 0 w miejsce najmniejszej wartości
vector[np.argmin(vector)] = 0

print("Wektor po wstawieniu 0 w miejsce najmniejszej wartości:")
print(vector)

Wektor po wstawieniu 0 w miejsce najmniejszej wartości:
[ 0 57 78 96 62 24 19 71 99 10]


13. Napisać skrypt, który w losowym wektorze Z znajdzie najbliższą wartość losowego skalara v.

In [23]:
Z = np.random.randint(0, 100, size=10)

# Losowy skalar v
v = np.random.randint(0, 100)

# Znalezienie indeksu najbliższej wartości w wektorze Z do wartości skalara v
nearest_index = np.abs(Z - v).argmin()

# Najbliższa wartość w wektorze Z do wartości skalara v
nearest_value = Z[nearest_index]

print("Losowy wektor Z:", Z)
print("Losowy skalar v:", v)
print("Najbliższa wartość w wektorze Z do wartości skalara v:", nearest_value)

Losowy wektor Z: [ 3 19 81 75  0 41 56 66 72 27]
Losowy skalar v: 47
Najbliższa wartość w wektorze Z do wartości skalara v: 41


14. Wygenerować losową macierz M o rozmiarach 5x8, a następnie zamienić kolejnością 2 losowo wskazane wiersze.

In [25]:
# Utworzenie losowej macierzy o rozmiarach 5x8
M = np.random.randint(1, 100, size=(5, 8))

# Wybór dwóch losowo wskazanych wierszy
rows_to_swap = np.random.choice(range(5), size=2, replace=False)

# Zamiana kolejności wybranych wierszy
M[rows_to_swap[0]], M[rows_to_swap[1]] = M[rows_to_swap[1]].copy(), M[rows_to_swap[0]].copy()

print("Macierz M po zamianie kolejności wierszy:")
print(M)

Macierz M po zamianie kolejności wierszy:
[[92 49 30 93 10 30 74 71]
 [ 8 35  8 65 40 97 10 35]
 [99 29 61 27  1  4 95 89]
 [66 46  3 71  7 78 36 95]
 [60 10  7 53 79 44 91  8]]


15. Wygenerować macierz o rozmiarach 5x5 wypełnioną dowolnymi kolejnymi wartościami, a następnie przetransformować macierz do postaci wektora kolumnowego zachowując wszystkie wartości.

In [27]:
# Utworzenie macierzy 5x5 wypełnionej kolejnymi wartościami
matrix = np.arange(1, 26).reshape(5, 5)

# Transpozycja macierzy do postaci wektora kolumnowego
vector = matrix.reshape(-1, 1)

print("Macierz:")
print(matrix)
print("\nWektor kolumnowy:")
print(vector)

Macierz:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Wektor kolumnowy:
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]
 [24]
 [25]]
